version: '3'

networks:
  mynetwork:
    driver: bridge

services:
  backend:
    build: ./backend
    ports:
      - 1337:1337
    command: bash -c "cd /usr/src/app && strapi start"
    networks:
      - mynetwork

    
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    command: bash -c "cd /usr/src/app && npm run dev"
    networks:
      - mynetwork
    


